# logind 容器兼容配置
# 放在 /etc/systemd/logind.conf.d/20-container.conf

[Login]
# 容器内不需要处理 VT 切换
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore

# 容器里不需要用户停机
KillUserProcesses=no

# 空闲时不要休眠
IdleAction=ignore
